//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Address
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public string country { get; set; }
        public string zip { get; set; }
        public string street { get; set; }
        public string number { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
